const TYPES = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  ADD_PRODUCT: "ADD_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  ADD_CART_ITEM: "ADD_CART_ITEM",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM"
};

export default TYPES;
